/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-05-08 16:23:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rendezVousCeduler_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <title>ClinicPlus | Dashboard</title>\n");
      out.write("        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>\n");
      out.write("        <!-- bootstrap 3.0.2 -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- font Awesome -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- Ionicons -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/ionicons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- daterange picker -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/daterangepicker/daterangepicker-bs3.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- iCheck for checkboxes and radio inputs -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/iCheck/all.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <!-- Bootstrap Color Picker -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/colorpicker/bootstrap-colorpicker.min.css\" rel=\"stylesheet\"/>\n");
      out.write("        <!-- Bootstrap time Picker -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/timepicker/bootstrap-timepicker.min.css\" rel=\"stylesheet\"/>\n");
      out.write("        <!-- Theme style -->\n");
      out.write("        <link href=\"");
request.getContextPath();
      out.write("resources/css/AdminLTE.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("          <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("          <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("    </head>\n");
      out.write("    <body class=\"skin-black\">\n");
      out.write("        <!-- header logo: style can be found in header.less -->\n");
      out.write("        <header class=\"header\">\n");
      out.write("            <a href=\"#\" class=\"logo\">\n");
      out.write("                <!-- Add the class icon to your logo image or logo icon to add the margining -->\n");
      out.write("                ClinicPlus\n");
      out.write("            </a>\n");
      out.write("            <!-- Header Navbar: style can be found in header.less -->\n");
      out.write("            <nav class=\"navbar navbar-static-top\" role=\"navigation\">\n");
      out.write("                <!-- Sidebar toggle button-->\n");
      out.write("                <a href=\"#\" class=\"navbar-btn sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("\n");
      out.write("                </a>\n");
      out.write("                <div class=\"navbar-right\">\n");
      out.write("                    <ul class=\"nav navbar-nav\">\n");
      out.write("                        \n");
      out.write("                        <!-- User Account: style can be found in dropdown.less -->\n");
      out.write("                        <li class=\"dropdown user user-menu\">\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"glyphicon glyphicon-user\"></i>\n");
      out.write("                                <span>Dr. Simon <i class=\"caret\"></i></span>\n");
      out.write("                            </a>\n");
      out.write("                            <ul class=\"dropdown-menu\">\n");
      out.write("                                <!-- User image -->\n");
      out.write("                                <li class=\"user-header bg-light-blue\">\n");
      out.write("                                    <img src=\"img/avatar/avatar_dr_simon.png\" class=\"img-circle\" alt=\"User Image\" />\n");
      out.write("                                    <p>\n");
      out.write("                                        Dr. Simon - Médecin\n");
      out.write("                                        <small>En poste depuis nov. 2012</small>\n");
      out.write("                                    </p>\n");
      out.write("                                </li>\n");
      out.write("                                <!-- Menu Body -->\n");
      out.write("                                <li class=\"user-body\">\n");
      out.write("                                    <div class=\"col-xs-4 text-center\">\n");
      out.write("                                        <a href=\"#\">Horaire</a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-xs-4 text-center\">\n");
      out.write("                                        <a href=\"#\">Dossiers</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <!-- Menu Footer-->\n");
      out.write("                                <li class=\"user-footer\">\n");
      out.write("                                    <div class=\"pull-left\">\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"pull-right\">\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-default btn-flat\">Déconnection</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("        <div class=\"wrapper row-offcanvas row-offcanvas-left\">\n");
      out.write("            <!-- Left side column. contains the logo and sidebar -->\n");
      out.write("            <aside class=\"left-side sidebar-offcanvas\">\n");
      out.write("                <!-- sidebar: style can be found in sidebar.less -->\n");
      out.write("                <section class=\"sidebar\">\n");
      out.write("                    <!-- Sidebar user panel -->\n");
      out.write("                    <div class=\"user-panel\">\n");
      out.write("                        <div class=\"pull-left image\">\n");
      out.write("                            <img src=\"img/avatar/avatar_dr_simon.png\" class=\"img-circle\" alt=\"User Image\" />\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pull-left info\">\n");
      out.write("                            <p>Hello, Dr.Simon</p>\n");
      out.write("\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-circle text-success\"></i> Online</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- search form -->\n");
      out.write("                    <form action=\"#\" method=\"get\" class=\"sidebar-form\">\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search...\"/>\n");
      out.write("                            <span class=\"input-group-btn\">\n");
      out.write("                                <button type='submit' name='seach' id='search-btn' class=\"btn btn-flat\"><i class=\"fa fa-search\"></i></button>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- /.search form -->\n");
      out.write("                    <!-- sidebar menu: : style can be found in sidebar.less -->\n");
      out.write("                    <ul class=\"sidebar-menu\">\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        <li class=\"treeview\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <i class=\"fa fa-edit\"></i> <span>Patients</span>\n");
      out.write("                                <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <ul class=\"treeview-menu\">\n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectPatientsListe\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Liste</a></li>\n");
      out.write("                                \n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectPatientsEnregistrer\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Enregistrer</a></li>\n");
      out.write("                                \n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectPatientsDossier\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Dossier</a></li>\n");
      out.write("                                \n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectPatientsNotification\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Notification</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"treeview\">\n");
      out.write("                            <a href=\"#\">\n");
      out.write("                                <i class=\"fa fa-table\"></i> <span>Rendez-Vous</span>\n");
      out.write("                                <i class=\"fa fa-angle-left pull-right\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <ul class=\"treeview-menu\">\n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectRendezVousListe\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Liste</a></li>\n");
      out.write("                                \n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectRendezVousCeduler\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Céduler</a></li>\n");
      out.write("                                \n");
      out.write("                                <li><a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectRendezVousConsultation\">\n");
      out.write("                                <i class=\"fa fa-angle-double-right\"></i> Consultation</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"");
request.getContextPath();
      out.write("/clinicplus/redirectCalendar\">\n");
      out.write("                                <i class=\"fa fa-calendar\"></i> <span>Calendrier</span>\n");
      out.write("                                <small class=\"badge pull-right bg-red\">3</small>\n");
      out.write("                            </a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </section>\n");
      out.write("                <!-- /.sidebar -->\n");
      out.write("            </aside>\n");
      out.write("\n");
      out.write("            <!-- Right side column. Contains the navbar and content of the page -->\n");
      out.write("            <aside class=\"right-side\">\n");
      out.write("\n");
      out.write("                <!-- Main content -->\n");
      out.write("                <section class=\"content\">\n");
      out.write("\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                       \n");
      out.write("                        <div class=\"col-md-6\">\n");
      out.write("                            <div class=\"box box-primary\">\n");
      out.write("                                <div class=\"box-header\">\n");
      out.write("                                    <h3 class=\"box-title\">Rendez-Vous</h3>\n");
      out.write("                                </div>\n");
      out.write("                               \n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>Spécialiste</label>\n");
      out.write("                                        <input type=\"text\" class=\"form-control\">\n");
      out.write("                                        <span class=\"input-group-addon\"><i class=\"fa fa-check\"></i></span>\n");
      out.write("                                    </div>\n");
      out.write("                                    \n");
      out.write("                                    <div class=\"input-group\">\n");
      out.write("                                    <label>Patient</label>\n");
      out.write("                                        <input type=\"text\" class=\"form-control\">\n");
      out.write("                                        <span class=\"input-group-addon\"><i class=\"fa fa-check\"></i></span>\n");
      out.write("                                    </div>\n");
      out.write("                                    \n");
      out.write("                                    <!-- Date and time range -->\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>Date et heure du rendez-vous:</label>\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <div class=\"input-group-addon\">\n");
      out.write("                                                <i class=\"fa fa-clock-o\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <input type=\"text\" class=\"form-control pull-right\" id=\"reservationtime\"/>\n");
      out.write("                                        </div><!-- /.input group -->\n");
      out.write("                                    </div><!-- /.form group -->\n");
      out.write("                                    \n");
      out.write("                                    <!-- phone mask -->\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <label>Téléphone:</label>\n");
      out.write("                                        <div class=\"input-group\">\n");
      out.write("                                            <div class=\"input-group-addon\">\n");
      out.write("                                                <i class=\"fa fa-phone\"></i>\n");
      out.write("                                            </div>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" data-inputmask='\"mask\": \"(999) 999-9999\"' data-mask/>\n");
      out.write("                                        </div><!-- /.input group -->\n");
      out.write("                                    </div><!-- /.form group -->\n");
      out.write("                                </div>\n");
      out.write("                            </div><!-- /.box -->\n");
      out.write("                        </div><!-- /.col (right) -->\n");
      out.write("                    </div><!-- /.row -->                      \n");
      out.write("\n");
      out.write("                </section><!-- /.content -->\n");
      out.write("            </aside><!-- /.right-side -->\n");
      out.write("        </div><!-- ./wrapper -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- jQuery 2.0.2 -->\n");
      out.write("        <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js\"></script>\n");
      out.write("        <!-- Bootstrap -->\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- InputMask -->\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/plugins/input-mask/jquery.inputmask.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/plugins/input-mask/jquery.inputmask.date.extensions.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/plugins/input-mask/jquery.inputmask.extensions.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- date-range-picker -->\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/plugins/daterangepicker/daterangepicker.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- bootstrap color picker -->\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/plugins/colorpicker/bootstrap-colorpicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- bootstrap time picker -->\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/plugins/timepicker/bootstrap-timepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- AdminLTE App -->\n");
      out.write("        <script src=\"");
request.getContextPath();
      out.write("resources/js/AdminLTE/app.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- AdminLTE for demo purposes -->\n");
      out.write("        <script src=\"js/AdminLTE/demo.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- Page script -->\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            $(function() {\n");
      out.write("                //Datemask dd/mm/yyyy\n");
      out.write("                $(\"#datemask\").inputmask(\"dd/mm/yyyy\", {\"placeholder\": \"dd/mm/yyyy\"});\n");
      out.write("                //Datemask2 mm/dd/yyyy\n");
      out.write("                $(\"#datemask2\").inputmask(\"mm/dd/yyyy\", {\"placeholder\": \"mm/dd/yyyy\"});\n");
      out.write("                //Money Euro\n");
      out.write("                $(\"[data-mask]\").inputmask();\n");
      out.write("\n");
      out.write("                //Date range picker\n");
      out.write("                $('#reservation').daterangepicker();\n");
      out.write("                //Date range picker with time picker\n");
      out.write("                $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});\n");
      out.write("                //Date range as a button\n");
      out.write("                $('#daterange-btn').daterangepicker(\n");
      out.write("                        {\n");
      out.write("                            ranges: {\n");
      out.write("                                'Today': [moment(), moment()],\n");
      out.write("                                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],\n");
      out.write("                                'Last 7 Days': [moment().subtract('days', 6), moment()],\n");
      out.write("                                'Last 30 Days': [moment().subtract('days', 29), moment()],\n");
      out.write("                                'This Month': [moment().startOf('month'), moment().endOf('month')],\n");
      out.write("                                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]\n");
      out.write("                            },\n");
      out.write("                            startDate: moment().subtract('days', 29),\n");
      out.write("                            endDate: moment()\n");
      out.write("                        },\n");
      out.write("                function(start, end) {\n");
      out.write("                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));\n");
      out.write("                }\n");
      out.write("                );\n");
      out.write("\n");
      out.write("                //iCheck for checkbox and radio inputs\n");
      out.write("                $('input[type=\"checkbox\"].minimal, input[type=\"radio\"].minimal').iCheck({\n");
      out.write("                    checkboxClass: 'icheckbox_minimal',\n");
      out.write("                    radioClass: 'iradio_minimal'\n");
      out.write("                });\n");
      out.write("                //Red color scheme for iCheck\n");
      out.write("                $('input[type=\"checkbox\"].minimal-red, input[type=\"radio\"].minimal-red').iCheck({\n");
      out.write("                    checkboxClass: 'icheckbox_minimal-red',\n");
      out.write("                    radioClass: 'iradio_minimal-red'\n");
      out.write("                });\n");
      out.write("                //Flat red color scheme for iCheck\n");
      out.write("                $('input[type=\"checkbox\"].flat-red, input[type=\"radio\"].flat-red').iCheck({\n");
      out.write("                    checkboxClass: 'icheckbox_flat-red',\n");
      out.write("                    radioClass: 'iradio_flat-red'\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                //Colorpicker\n");
      out.write("                $(\".my-colorpicker1\").colorpicker();\n");
      out.write("                //color picker with addon\n");
      out.write("                $(\".my-colorpicker2\").colorpicker();\n");
      out.write("\n");
      out.write("                //Timepicker\n");
      out.write("                $(\".timepicker\").timepicker({\n");
      out.write("                    showInputs: false\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("\t\t\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("l>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
